In [3]:
#zeros() ones()
import numpy as np

In [9]:
y=np.ones((2,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]]


In [13]:
x=np.zeros((2,3))
print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


In [19]:
z=np.ones((3,3),dtype=[('m','int'),('n','float')])
print(z)
#first is int and second one is float

[[(1, 1.) (1, 1.) (1, 1.)]
 [(1, 1.) (1, 1.) (1, 1.)]
 [(1, 1.) (1, 1.) (1, 1.)]]


In [15]:
a=np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])
for i in a:
    for j in i:
        print(j,end=' ')
    print()

10 20 30 
40 50 60 
70 80 90 


In [27]:
print("Row 0 ",a[0])
print("Row 0 ",a[1])

Row 0  [10 20 30]
Row 0  [40 50 60]


In [31]:
print(a[0:2])

[[10 20 30]
 [40 50 60]]


In [35]:
print(a[1:])

[[40 50 60]
 [70 80 90]]


In [37]:
print(a[::-1])


[[70 80 90]
 [40 50 60]
 [10 20 30]]


In [43]:
print((a[0:-1]))

[[10 20 30]
 [40 50 60]]
